models/UserTypes.php
<?
namespace app\models;

use yii\db\ActiveRecord;

class UserTypes extends ActiveRecord {
    public static function tableName()
    {
        return 'user_types';
    }
    public static function GetList($exclude = -1){
    	$retval = [];
    	$retval[''] = '(не задан)';
    	foreach(UserTypes::find()->all() as $i){
    		if($i->id != $exclude)
	    		$retval[$i->id] = $i->title;
    	}
    	
    	return $retval;
    }
}

controllers/UserController.php
<?
namespace app\controllers;

use rmrevin\yii\ulogin\AuthAction;
use yii\web\Controller;
use Yii;
use app\models\LoginForm;
use app\models\ResetPassword;
use app\models\User;
use app\models\MailTemplate;
use app\models\Order;
use app\models\Payments;
use app\models\ajaxFileUploads;
use yii\web\UploadedFile;
use yii\helpers\Url;
use Html2Text\Html2Text;


class UserController extends Controller
{
	
	private $doUlogin = false;
	
	public function beforeAction($action)
	{            
	    if (in_array($action->id, ['ulogin'])) {
	        $this->enableCsrfValidation = false;
	    }

    	return parent::beforeAction($action);
	}

    public function actions()
    {
        return [
            // ...
            'ulogin' => [
                'class' => AuthAction::className(),
                'successCallback' => [$this, 'uloginSuccessCallback'],
                'errorCallback' => function($data){
                    \Yii::error($data['error']);
                },
            ]
        ];
    }
    

    public function actionSetpass($token){
    	$model = User::findOne(['reset'=>$token]);
    	if(!$model)
	    	return $this->render('reset', ['model'=>$model, 'status'=>3]);
			
		$model->scenario = 'setpass';
		if($model->load(Yii::$app->request->post() )){
			if($model->validate()){
				$model->password = $model->password1;
				$model->reset = null;
				$model->save();
				return $this->redirect(['user/login']);
				
			}
		}
			
		return $this->render('setpass', ['model'=>$model]);

    }
    
    public function actionMt($to){

            $message = Yii::$app->mailer->compose();
            
            return $message -> setFrom('info@eventblaster.ru')
		    	->setTo($to)
		    	->setSubject('test')
    	    	->setHtmlBody('test')
    	    	->setTextBody((new Html2Text('test'))->getText())
		    	->send();

    }

    
    public function actionReset()
    {
        $model = new ResetPassword();
        
		if ($model->load(Yii::$app->request->post())
		        && Yii::$app->recaptcha->verifyResponse($_SERVER['REMOTE_ADDR'], Yii::$app->request->post('g-recaptcha-response')))
		{
			$user = User::findAll(['username'=>$model->username]);
			if(!$user) // не найдена почта
		    	return $this->render('reset', ['model'=>$model, 'status'=>2]);
		    	
		    foreach($user as $_user){
			    $reset = md5($_user->id . time());
			    
			    $_user->reset = $reset;
			    MailTemplate::sendMail($_user->username, 'PASSWORD_RESET', [
			    		'URL' => Yii::$app->request->hostInfo . Url::toRoute(['user/setpass', 'token'=>$reset]),
			    		'FIO' => $_user->fio
			    	]);
			    }
			    
			    $_user->save();
		    	
	    	return $this->render('reset', ['model'=>$model, 'status'=>1]);
		}
        
    	return $this->render('reset', ['model'=>$model, 'status'=>0]);
    }
    
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->render('switch');
        }
        $model = new LoginForm();
        
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->successRedirect();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionFav_toggle($id){

    	if(Yii::$app->user->getIsGuest())
    		return $this->goHome();
    		
    	$model = Yii::$app->user->identity;
		if(!$model)
			throw new \yii\web\NotFoundHttpException();
			
		$ids = $model->fav_ids ? preg_split('/;/', $model->fav_ids) : [];
		if(!in_array($id, $ids)){ // добавить
			$ids[] = $id;
			
			$model->fav_ids =  join(';', $ids);
			$model->save();
			return JSON_encode(['addClass'=>'in-favs']);
		} else { // убавить
			$ids = array_diff($ids, [$id]);
			$model->fav_ids =  join(';', $ids);
			$model->save();
			return JSON_encode(['removeClass'=>'in-favs']);
			
		}
    	
    }
    
    public function actionChoose(){
    	if(Yii::$app->user->getIsGuest())
    		return $this->goHome();
    		
    	$id = Yii::$app->user->id;
    	$model = User::findIdentity($id);
		if(!$model)
			throw new \yii\web\NotFoundHttpException();

		if($model->user_type_id)
			$this->goHome();
    	if($model->load(Yii::$app->request->post()) && $model->validate()){
    		$model->save();
	    	if($model->user_type_id){
	    		$model->registerGreeting();
	    	}

    		$this->goHome();
    	}
			
		return $this->render('choose', ['model'=>$model]);
    }


    public function actionRegister($type=NULL){
    	$model = new LoginForm();
    	
    	$model->type = $type;

		$order_id = Yii::$app->session->get('attach_order');
		$ref_id = Yii::$app->session->get('ref');


		if($order_id){
			$order = Order::findByPk($order_id);
	    	if($order){
		    	$model->username = $order->email;
	    	}
		}
		
		if($ref_id)
			$model->ref_parent = $ref_id;

        if ($model->load(Yii::$app->request->post()) && $model->register()) {
			return $this->successRedirect();
        }

        return $this->render('login', [
        	'model' => $model,
        	'message' => 'Регистрация',
        	]);
    }

	public function actionReviews($id, $type = 'total'){
		$user = User::findIdentity($id);
		if(!$user)
			throw new \yii\web\NotFoundHttpException();
			
		return $this->render('reviews', ['reviews'=>$user->_reviews, 'user'=>$user, 'type'=>$type]);
	}
    
    public function actionView($id)
    {
    	$model = User::findIdentity($id);
    	
		if(!$model)
			throw new \yii\web\NotFoundHttpException();
    	
    	$me = Yii::$app->user->getIsGuest() ? false : Yii::$app->user->id;
    	$meAdmin = User::isThisRole(User::TYPE_ADMIN);
    	
    	$hasWriteAccess = $meAdmin || ($me == $id);
    	
    	if(User::isThisRole(User::TYPE_SERVER))
    		$model->scenario = 'server_profile';
    	
    	if($hasWriteAccess){
    		// попробовать автозаполнение из заказов
    		if(!$model->fio || !$model->email || !$model->phone){
    			$order = Order::findOne(['owner_id'=>$id]);
    			if($order){
	    			if(!$model->fio)
	    				$model->fio = $order->fio;
	    			if(!$model->email)
	    				$model->email = $order->email;
	    			if(!$model->phone)
	    				$model->phone = $order->phone;
    			}
    		}

	    	if($model->load(Yii::$app->request->post()) && $model->validate()){
	    		
	    		
	    		if($model->password1)
	    			$model->password = $model->password1;
	    		
	            $file = UploadedFile::getInstanceByName('User[avatar]');
	            if($file){
		        	$name = md5($file->getBaseName() . $file->size) . '.' . $file->getExtension();
		        	$fname = Yii::getAlias('@webroot/uploads/' . $name);
		            if($file->saveAs($fname)){
		            	$model->avatar = $name;
		            }
	            }
	            
	            if(!$meAdmin) {
	            	$moderatedChanged = ($model->comments != $model->getOldAttribute('comments'));
	            	if($moderatedChanged)
	            		$model->moderated = false;
	            }
	            
	            if( ($model->getOldAttribute('email') != $model->email) && ($model->getOldAttribute('email') == $model->username) ){
	            	// исправить username при смене почты, если почта совпадает с юзернеймом
	            	$model->username = $model->email;
	            }
	            
	    		$model->save();
	    		if(isset(Yii::$app->request->post()['save'])){
	    			if(User::isThisRole(User::TYPE_ADMIN))
		    			$this->redirect(Url::toRoute('userlist/index'));
		    		else
		    			$this->goBack();
	    		}
	    	}
	    	return $this->render('view-writeable', ['model'=>$model]);
    	} else {
    		if(Yii::$app->request->isPost)
				return $this->goBack();
			else
				return $this->render('view-readonly', ['model'=>$model]);
    	}
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	protected function successRedirect(){
			$backurl = Yii::$app->request->getQueryParam('backurl');
			if($backurl){
				return Yii::$app->response->redirect($backurl);
			}
			else
				return $this->goHome();
		
	}

    public function uloginSuccessCallback($attributes)
    {
    	
		$model = new LoginForm();
		
		Yii::$app->user->login($model->ulogin($attributes));
		return $this->successRedirect();
    }
}
?>

views/user/_reviews_list.php
<?
use yii\helpers\Url;

$rates = [
		'-2'=>'Очень плохо',
		'-1'=>'Плохо',
		'0' => 'Нормально',
		'1' => 'Хорошо',
		'2' => 'Отлично!'
		];
		
?>

<div class="reviews-list">
	<? if(!$reviews->count()) { ?>
		Нет отзывов
	<? } else { ?>
		<? foreach($reviews->all() as $review) { ?>
			<div class="review-item">
				<? if(get_class($review) != 'app\models\ImportedReviews') { ?>
				<div class="fio">
					Заказчик: <b><? echo $review->owner->fio ?></b>
				</div>
				<div class="project">
					Проект: <b><? echo $review->title ?></b>
				</div>
				<div class="rate">
					Оценка: <b><? echo $rates[$review->feedback_rate] ?></b>
				</div>
				<i class="fa fa-quote-left pull-left"></i>
				<div class="review-body">
					<div class="review-text">
						<? echo $review->feedback_text ?>
					</div>
				</div>
				<i class="fa fa-quote-right"></i>
				<? } else { ?>
				<div class="name">
					<? echo $review->name ?>
					<span class="date"><? echo date('d-m-Y', $review->created) ?></span>
				</div>
				<i class="fa fa-quote-left pull-left"></i>
				<div class="review-body">
					<div class="review-text">
						<? echo $review->text ?>
					</div>
				</div>
				<i class="fa fa-quote-right"></i>
				<? } ?>
			</div>
		<? } ?>
	<? } ?>
</div>

views/user/choose.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\UserTypes;
use app\models\User;
use yii\helpers\Url;

?>
<div class="inner-section clearfix user-type-choose">
<? $form = ActiveForm::Begin(); ?>

<h1>Выберите свою роль</h1>

<div class="row text-center">
	<div class="col-sm-6">
		<label for="client">
		<h2>Заказчик</h2>
		<p>Хочу разместить заказ на проведение мероприятий и выбирать лучшие предложения от организаторов мероприятий!</p>
		<img src="/img/p3.png" alt="">
		</label>
	</div>
	<div class="col-sm-6">
		<label for="servitor">
		<h2>Организатор</h2>
		<p>Хочу просматривать заказы по организации мероприятий и предлагать свои услуги заказчикам!</p>
		<img src="/img/p4.png" alt="">
		</label>
	</div>
</div>

<input type="radio" name="User[user_type_id]" value="2" id="client">
<input type="radio" name="User[user_type_id]" value="3" id="servitor">

<? ActiveForm::end(); ?>
</div>

views/user/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use rmrevin\yii\ulogin\ULogin;
use yii\helpers\Url;


$this->title = isset($message) ? $message : 'Вход на сайт';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<div class="left-chuvak">
	</div>
	<div class="login-internal">
	    <h3 class="login-options">
	    	<? $titles = ['Регистрация' => Url::toRoute(['user/register']), 'Вход на сайт'  => Url::toRoute(['user/login'])];
	    	if(!in_array($this->title, $titles))
	    		$titles[$this->title] = '';
	    	foreach($titles as $title => $link) {
	    		if($title == $this->title)
	    			echo '<span>' . $title . '</span>';
	    		else
	    			echo '<a href="'.$link.'">' . $title . '</a>';
	    	}
	    	?>
	    </h3>
	
	    <?php $form = ActiveForm::begin([
	        'id' => 'login-form'
	    ]); ?>
	
        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
                <?= Html::submitButton($this->title, ['class' => 'btn btn-primary login-button', 'name' => 'login-button']) ?>
				<? echo ULogin::widget([
				    // widget look'n'feel
				    'display' => ULogin::D_PANEL,
				
				    // required fields
				    'fields' => [ULogin::F_FIRST_NAME, ULogin::F_LAST_NAME, ULogin::F_EMAIL, ULogin::F_PHONE, ULogin::F_CITY, ULogin::F_COUNTRY, ULogin::F_PHOTO_BIG],
				
				    // optional fields
				    'optional' => [ULogin::F_BDATE],
				
				    // login providers
				    'providers' => [ULogin::P_VKONTAKTE, ULogin::P_FACEBOOK, ULogin::P_TWITTER, ULogin::P_GOOGLE, ULogin::P_ODNOKLASSNIKI],
				
				    // login providers that are shown when user clicks on additonal providers button
				    'hidden' => [],
				
				    // where to should ULogin redirect users after successful login
				    'redirectUri' => Url::toRoute(['user/ulogin', 'backurl'=>Yii::$app->request->getQueryParam('backurl')]),
				
				    // optional params (can be ommited)
				    // force widget language (autodetect by default)
				    'language' => ULogin::L_RU,
				
				    // providers sorting ('relevant' by default)
				    'sortProviders' => ULogin::S_RELEVANT,
				
				    // verify users' email (disabled by default)
				    'verifyEmail' => '0',
				
				    // mobile buttons style (enabled by default)
				    'mobileButtons' => '1',
				]); ?>
				<br>
				<div class="">
				<a href="<? echo Url::toRoute(['user/reset'])?>">Забыли пароль?</a>
				<br>
				<a href="<? echo Url::toRoute(['site/contact'])?>">Служба технической поддержки</a>
				</div>
        </div>
	
	</div>
	<div class="right-chuvak">
	</div>
	
    <?php ActiveForm::end(); ?>
</div>

views/user/reset.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use richweber\recaptcha\Captcha;


$this->title = 'Восстановление пароля';
?>
<div class="site-login">
    <?php $form = ActiveForm::begin(['id'=>'login-form']); ?>
	<div class="left-chuvak">
	</div>
	<div class="login-internal text-center">
		
	    <h3>Восстановление пароля</h3>

		<? if($status === 0) { ?>
	        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
	        <?= Captcha::widget() ?>
	        <?= Html::submitButton('Восстановить пароль', ['class' => 'btn btn-primary login-button', 'name' => 'login-button']) ?>
        <? } ?>
		<? if($status === 1) { ?>
		    <p class="well">Ссылка для восстановления пароля отправлена на электронную почту</p>
        <? } ?>
		<? if($status === 2) { ?>
		    <p class="well">Не найден такой пользователь</p>
        <? } ?>
		<? if($status === 3) { ?>
		    <p class="well">Ссылка недействительна. Возможно, вы пытаетесь повторно пройти по ссылке, уже использованной ранее для восстановления пароля.</p>
        <? } ?>

	</div>
	<div class="right-chuvak">
	</div>
	
    <?php ActiveForm::end(); ?>
</div>

views/user/reviews.php
<?
use yii\bootstrap\Tabs;

$this->title = "Отзывы пользователя ".$user->fio;

?>

<div class="inner-section clearfix">
<?
$items = [
    	[
    		'label' => 'Все отзывы ('.$reviews['total']->count().')',
    		'active' => ($type == 'total'),
    		'content' => $this->render('_reviews_list', ['reviews'=>$reviews['total']])
		],
    	[
    		'label' => 'Положительные ('.$reviews['positive']->count().')',
    		'active' => ($type == 'positive'),
    		'content' => $this->render('_reviews_list', ['reviews'=>$reviews['positive']])
		],
    	[
    		'label' => 'Нейтральные ('.$reviews['neutral']->count().')',
    		'active' => ($type == 'neutral'),
    		'content' => $this->render('_reviews_list', ['reviews'=>$reviews['neutral']])
		],
    	[
    		'label' => 'Негативные ('.$reviews['negative']->count().')',
    		'active' => ($type == 'negative'),
    		'content' => $this->render('_reviews_list', ['reviews'=>$reviews['negative']])
		],
    	[
    		'label' => 'Отзывы с других сайтов ('.$reviews['imported']->count().')',
    		'active' => ($type == 'imported'),
    		'content' => $this->render('_reviews_list', ['reviews'=>$reviews['imported']])
		]
	];

echo Tabs::widget([
    'items' => $items
    ]);
?>
</div>

views/user/server-readonly.php
<?
use app\models\Tags;
use app\models\User;
use app\models\Regions;
use kartik\select2\Select2;
use yii\helpers\Url;
use newerton\fancybox\FancyBox;
use yii\helpers\Html;

?>
<br>
		<table>
			<tr>
			<? if($model->taglist_ids) : ?>
			<td>
			<div class="services">
				<div class="taglist">
					<label>Услуги:</label>
						<ul>
						<? foreach($model->_taglist_text as $i)
							echo '<li><i class="fa fa-tag"></i> ' . Html::encode($i->title) . "</li> "
						?>
						</ul>
					</div>
				</div>
			</td>
			<? endif ?>
			<td>
				<label>Город(а): </label>
				<? echo $model->_region_title; ?>
			</td>
			<td>
				<label>Тип организатора:</label>
				<? echo $model->_event_type_title; ?>
			</td>
			</tr>
		</table>


<? if(User::isThisRole(User::TYPE_ADMIN)) echo $form->field($model, '_pay_until')->textInput(['readonly'=>'true']); ?>
<? if($model->_portfolio_count) { ?>
<label>Портфолио</label>
<div class="portfolio" data-ajax-embed="<? echo Url::toRoute(['portfolio/index', 'id'=>$model->id])?>"></div>
<? echo FancyBox::widget([
    'target' => 'a[data-fancybox-group]',
    'helpers' => true,
    'mouse' => true,
    'config' => [
        'maxWidth' => '90%',
        'maxHeight' => '90%',
        'playSpeed' => 7000,
        'padding' => 0,
        'fitToView' => false,
        'width' => '70%',
        'height' => '70%',
        'autoSize' => false,
        'closeClick' => false,
        'openEffect' => 'elastic',
        'closeEffect' => 'elastic',
        'prevEffect' => 'elastic',
        'nextEffect' => 'elastic',
        'closeBtn' => false,
        'openOpacity' => true,
        'helpers' => [
            'title' => ['type' => 'float'],
            'buttons' => [],
            'thumbs' => ['width' => 68, 'height' => 50],
            'overlay' => [
                'css' => [
                    'background' => 'rgba(0, 0, 0, 0.8)'
                ]
            ]
        ],
    ]
]); ?>
<? } ?>

views/user/setpass.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use richweber\recaptcha\Captcha;

$this->title = 'Восстановление пароля';
?>
<div class="site-login">
    <?php $form = ActiveForm::begin(['id'=>'login-form']); ?>
	<div class="left-chuvak">
	</div>
	<div class="login-internal">
	    <h3 class="text-center">Восстановление пароля</h3>
	    <? echo $form->field($model, 'username')->textInput(['readonly'=>'readonly']); ?>
	    <? echo $form->field($model, 'password1')->textInput(); ?>
	    <? echo $form->field($model, 'password2')->textInput(); ?>
	    

		<button class="btn btn-default">Сменить пароль</button>
		<div class="clearfix"></div>

	</div>
	<div class="right-chuvak">
	</div>
	
    <?php ActiveForm::end(); ?>
</div>

views/user/switch.php
Войти под другим пользователем
или
Вернуться на главную

views/user/view-readonly.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\User;
use app\models\EventType;
use kartik\file\FileInput;
use yii\helpers\Url;

$this->title = $model->fio ? $model->fio : 'Просмотр профиля';

?>
<div class="inner-section clearfix">
<? $form = ActiveForm::Begin(); ?>
<h2><? echo $this->title?>
		<? if($model->user_type_id == USER::TYPE_SERVER) { ?>
		<? $reviews = $model->_reviews_count; ?>
		<span class="reviews">
			<? unset($reviews['total']); foreach($reviews as $key=>$v){ ?>
				<a href="<? echo Url::toRoute(['user/reviews', 'id'=>$model->id, 'type'=>$key])?>" class="<?=$key?>"><?=$reviews[$key]?></a>
			<? } ?>
		</span>
		<? } ?>
</h2>

<? if($model->_paid_now) { ?>
<div class="row">
	<div class="col-sm-3">
		<? echo $form->field($model, 'phone')->textInput(['readonly'=>'true']); ?>
	</div>
	<div class="col-sm-9">
		<div class="row">
			<div class="col-sm-6">
				<? echo $form->field($model, 'fio')->textInput(['readonly'=>'true']); ?>
			</div>
			<div class="col-sm-6">
				<? echo $form->field($model, 'email')->textInput(['readonly'=>'true']);; ?>
			</div>
		</div>
	</div>
</div>

<? } ?>
<div class="row">
	<div class="col-sm-3">
		<label>Фото</label>
		<div class="avatar">
			<? echo $model->avatar ? Yii::$app->imageCache->thumb(Yii::getAlias('@web/uploads/'.$model->avatar)) :
			'<img height="150" width="150" src="/img/no-photo.png">' ?>
		</div>
	</div>
	<div class="col-sm-9">
		<label>О себе:</label>
		<? if($model->moderated) { ?>
		<? echo Html::encode($model->comments); ?>
		<? } else { ?>
		Текст еще не прошел модерацию, зайдите позже
		<? } ?>
	</div>
</div>



<? if($model->user_type_id == User::TYPE_SERVER)echo $this->renderFile('@app/views/user/server-readonly.php', ['model'=>$model, 'form'=>$form]); ?>
<? if(!Yii::$app->request->get('newwin')) : ?>
<a class="btn btn-primary" href="<?=Yii::$app->request->referrer;?>">Назад</a>
<? endif ?>

<? ActiveForm::end(); ?>
</div>

views/user/view-writeable.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\UserTypes;
use app\models\User;
use app\models\EventType;
use kartik\file\FileInput;
use yii\helpers\Url;
use kartik\date\DatePicker;

$this->title = 'Редактирование профиля';

?>
<div class="inner-section clearfix hilite-required">
<? $form = ActiveForm::Begin(['options'=>['enctype'=>'multipart/form-data']]); ?>
<h2><? echo $this->title?>
		<? if($model->user_type_id == USER::TYPE_SERVER) { ?>
		<? $reviews = $model->_reviews_count; ?>
		<span class="reviews">
			<? unset($reviews['total']); foreach($reviews as $key=>$v){ ?>
				<a href="<? echo Url::toRoute(['user/reviews', 'id'=>$model->id, 'type'=>$key])?>" class="<?=$key?>"><?=$reviews[$key]?></a>
			<? } ?>
		</span>
		<? } ?>
</h2>
<div class="row">
	<div class="col-sm-3">
		<? echo $form->field($model, 'avatar')->widget(FileInput::classname(), [
			    'options' => ['accept' => 'image/*'],
		        'pluginOptions' => [
		        'showPreview' => true,
		        'showCaption' => true,
		        'showRemove' => false,
		        'showUpload' => false,
		        'initialPreview'=>
			        $model->avatar ? [ Yii::$app->imageCache->thumb(Yii::getAlias('@web/uploads/'.$model->avatar)) ] : [],
			        'uploadExtraData' => [
			        	'owner'=>$model->id
			        ],
			        'maxFileCount' => 1
			    ]
		]); ?>
	</div>
	<div class="col-sm-9">
		<div class="row">
			<div class="col-sm-4">
				<? echo $form->field($model, 'fio')->textInput(); ?>
			</div>
			<div class="col-sm-4">
				<? echo $form->field($model, 'email')->textInput(); ?>
			</div>
			<div class="col-sm-4">
				<? echo $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
				    'mask' => '+7 (999) 999-99-99',
				]) ?>
			</div>
		</div>
		<? echo $form->field($model, 'comments')->textArea(); ?>
	</div>
</div>
<? if(User::isThisRole(User::TYPE_ADMIN)) { ?>
<div class="row">
	<div class="col-sm-3">
		<? echo $form->field($model, 'id')->textInput(['readonly' => true]); ?>
	</div>
	<div class="col-sm-9">
		<div class="row">
			<div class="col-sm-6">
				<? echo $form->field($model, 'username')->textInput(['readonly' => true]); ?>
			</div>
			<div class="col-sm-6">
				<? echo $form->field($model, 'email'); ?>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-3">
		<? echo $form->field($model, 'moderated')->dropDownList(
				[0=>'Нет',1=>'Да']
		); ?>
	</div>
	<div class="col-sm-9">
		<div class="row">
			<div class="col-sm-6">
				<? echo $form->field($model, 'user_type_id')->dropDownList(
						UserTypes::GetList()
				); ?>
			</div>
			<div class="col-sm-6">
				<? echo $form->field($model, '_pay_until')->widget(DatePicker::classname(), [
						'language' => 'ru',
						'removeButton' => false,
					    'pluginOptions' => [
					        'autoclose'=>true,
					        'format' => 'dd-mm-yyyy'
					    ]
				]); ?>
			</div>
		</div>
	</div>
</div>

<? } ?>






<? if($model->user_type_id == User::TYPE_SERVER)echo $this->render('@app/views/user/server-writeable.php', ['model'=>$model, 'form'=>$form]); ?>


<div class="form-group">
	<?= Html::submitButton('Сохранить', ['name'=>'save', 'class' => 'btn btn-primary']) ?>
	<a class="btn btn-default pass-unhide" href="#changepass">Изменить пароль</a>
</div>
<div class="row">
	<div class="col-sm-3">
		<div id="changepass" class="<? echo !$model->password1 && !$model->password2 ? 'hidden' : ''?>">
			<div class="form-group">
					<? echo $form->field($model, 'password1')->textInput(); ?>
			</div>
			<div class="form-group">
					<? echo $form->field($model, 'password2')->textInput(); ?>
			</div>
			<?= Html::submitButton('Задать пароль', ['name'=>'save', 'class' => 'btn btn-primary']) ?>
		</div>
	
	</div>
</div>

<? ActiveForm::end(); ?>
</div>