controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Messages;
use app\models\ContactForm;
use app\models\User;
use app\models\Order;
use app\models\Moderation;
use app\models\Statistics;
use app\models\SystemSettings;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'thumb' => 'iutbay\yii2imagecache\ThumbAction',

        ];
    }

    public function actionIndex()
    {
    	if(Yii::$app->user->getIsGuest()){
    		$orders = Order::find()->count();
    		$servitors = User::find()->andWhere(['user_type_id'=>User::TYPE_SERVER])->count();
    		return $this->render('index', ['orders'=>$orders, 'servitors'=>$servitors]);
    	}
    	else
    		return $this->redirect(['site/cabinet']);
    }
    
    public function actionRef($id){
    	Yii::$app->session->set('ref', $id);
    	return $this->goHome();
    }
    
    public function actionPhone($phone){
    	$model = new Order();
    	$model->phone_add = $phone;
    	$model->obtainvericode();
    	return '[]';
    }
    
    public function actionCabinetClient(){
		$user = User::findIdentity(Yii::$app->user->id);
		$orders = Order::getOrders($user->id);
		$messages = Messages::GetList($user->id);
		$favs = $user->_fav_ids;

		if( (count($orders) > 0) && (!$user->profileCompleted()) )
			return $this->redirect(['user/view', 'id'=>$user->id]);
			
		return $this->render('cabinet_client', ['user'=>$user, 'orders'=>$orders, 'messages'=>$messages, 'favs'=>$favs]);
    }
    public function actionCabinetPartner(){
		$user = User::findIdentity(Yii::$app->user->id);
		return $this->render('cabinet_partner', ['user'=>$user]);
    }
    public function actionCabinetServer(){
		$user = User::findIdentity(Yii::$app->user->id);
		$orders = Order::getOrders($user->id);
		$messages = Messages::GetList($user->id);
		return $this->render('cabinet_server', ['user'=>$user, 'orders'=>$orders, 'messages'=>$messages]);
    }
    public function actionCabinetAdmin(){
		$moderation = new Moderation();
		$statistics = new Statistics();
		return $this->render('cabinet_admin', ['moderation'=>$moderation, 'statistics'=>$statistics]);
    }
    
    public function actionCabinet(){
    	
    	if(Yii::$app->user->getIsGuest())
			return $this->goHome();

    	if(User::isThisRole(User::TYPE_ADMIN))
    		return $this->actionCabinetAdmin();

    	if(User::isThisRole(User::TYPE_CLIENT))
    		return $this->actionCabinetClient();

    	if(User::isThisRole(User::TYPE_SERVER))
    		return $this->actionCabinetServer();
    		
    	if(User::isThisRole(User::TYPE_PARTNER))
    		return $this->actionCabinetPartner();
    		
    	$this->redirect(['user/choose']);

    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/cabinet_admin.php
<?
use yii\helpers\Url;
$this->title = "Данные о системе";
?>
<div class="inner-section clearfix">
	<h2>Данные о системе</h2>
	<h3>Модерация</h3>
	<? if(count($moderation->items) == 0) { ?>
	<p>Нет задач по модерации</p>
	<? } else foreach($moderation->items as $m) { ?>
	<p><? echo $m['title']?> <? echo $m['count']; ?> <a href="<? echo $m['link']?>">Просмотреть</a></p>
	<? } ?>
	<h3>Статистика</h3>
	<? if(count($statistics->items) == 0) { ?>
	<p>Нет данных статистики</p>
	<? } else foreach($statistics->items as $m) { ?>
	<p><? echo $m['title']?> <? echo $m['count']; ?></p>
	<? } ?>

</div>

views/site/cabinet_client.php
<?
use yii\helpers\Url;
$this->title = "Личный кабинет заказчика";
?>
<div class="inner-section cabinet clearfix">
	<h2><? echo $this->title?></h2>
	<div class="row">
		<div class="col-sm-7">
			<? if(!$user->profileCompleted()) { ?>
			<p>Пожалуйста, не забудьте заполнить данные <a href="<? echo Url::toRoute(['user/view', 'id'=>$user->id])?>">профиля заказчика</a></p>
			<? } ?>
			
			<h3>Ваши заказы</h3>
			<p>
				<a href="<? echo Url::toRoute(['orders/view', 'id'=>'new']); ?>" class="btn btn-default"><i class="fa fa-plus"></i> Добавить заказ</a>
				<a href="<? echo Url::toRoute(['orders/index']); ?>" class="btn btn-default"><i class="fa fa-glass"></i>Посмотреть мои заказы</a>
			</p>
			<p>
				Добавьте заказ с описанием мероприятия, чтобы получать предложения.
				<? if(count($orders)) { ?> Вы уже разместили <? echo count($orders) ?> заказов. <? } ?>
			</p>
			
			<h3>Переговоры</h3>
			<p>
				<a href="<? echo Url::toRoute(['message/index']) ?>" class="btn btn-default"><i class="fa fa-send"></i> Посмотреть переписку</a>
			</p>
			<p>
				Вы ведете общение с <? echo $messages->count ?> потенциальными организаторами.
			</p>
		
			<? if(count($favs)) { ?>
			<h3>Избранные организаторы</h3>
			<p>
				<a href="<? echo Url::toRoute(['userlist/favs']) ?>" class="btn btn-default"><i class="fa fa-bookmark"></i> Посмотреть список</a>
			</p>
			<p>
				Вы отметили <? echo count($favs) ?> организаторов как избранных.
			</p>
			<? } ?>
			<? echo $this->render('referal'); ?>
		</div>
		<div class="col-sm-5 hidden-xs text-center">
			<? echo $this->render('@app/views/site/greetings') ?>
		</div>
	</div>
</div>

views/site/cabinet_partner.php
<?
use yii\helpers\Url;
$this->title = "Личный кабинет партнера";
?>
<div class="inner-section cabinet clearfix">
	<h2><? echo $this->title?></h2>
	<div class="row">
		<div class="col-sm-7">
			<? echo $this->render('referal'); ?>
			<img src="/img/partners.png" alt="" class="img-responsive">
		</div>
		<div class="col-sm-5 hidden-xs text-center">
			<? echo $this->render('@app/views/site/greetings') ?>
		</div>
	</div>
</div>

views/site/cabinet_server.php
<?
use yii\helpers\Url;
$this->title = "Личный кабинет организатора мероприятий";
?>
<div class="inner-section clearfix">
	<h2><? echo $this->title?></h2>
		<div class="row">
			<div class="col-sm-7">
				<? if(!$user->fio || !$user->phone) { ?>
				<p>Пожалуйста, не забудьте заполнить данные <a href="<? echo Url::toRoute(['user/view', 'id'=>$user->id])?>">профиля исполнителя</a></p>
				<? } ?>
				<h3>Заказы</h3>
				<p>Поиск заказов на организацию мероприятия</p>
				<a href="<? echo Url::toRoute(['orders/index']); ?>" class="btn btn-default">Поиск заказов</a>
				<h3>Отзывы</h3>
				<p>Оставить заявку на перенос отзывов с другого сайта.</p>
				<a href="<? echo Url::toRoute(['orders/import']); ?>" class="btn btn-default">Импорт отзывов</a>
				<h3>Оплата подписки</h3>
				<p>
					<? if($user->_paid_now) { ?>
					Ваша подписка оплачена до: <? echo date('d-m-Y H:i', $user->pay_until); ?>
					<? } else { ?>
					Ваша подписка не оплачена. <a href="<? echo Url::toRoute(['payments/subscribe']); ?>" class="btn btn-default"><i class="fa fa-dollar"></i> Оплатить подписку</a>
					<? } ?>
				</p>
				<h3>Переговоры</h3>
				<p>
					Вы ведете переговоры с заказчиками по <? echo $messages->count ?> проектам.
					<a href="<? echo Url::toRoute(['message/index']) ?>" class="btn btn-default"><i class="fa fa-send"></i> Посмотреть сообщения</a>
				</p>
				<? echo $this->render('referal'); ?>
			</div>
		<div class="col-sm-5 hidden-xs text-center">
			<? echo $this->render('@app/views/site/greetings') ?>
		</div>
	</div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Задайте свой вопрос';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inner-section clearfix">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Спасибо за сообщение, ответим Вам как можно скорее!
        </div>

    <?php else: ?>
        <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
        <p>
            Обратная связь. Напишите Ваш вопрос, и мы ответим Вам!
        </p>

        <div class="row">
            <div class="col-sm-4">
                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>
			</div>
            <div class="col-sm-4">
                    <?= $form->field($model, 'email') ?>
			</div>
            <div class="col-sm-4">
                    <?= $form->field($model, 'subject') ?>
			</div>

        </div>
        <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

        <div class="form-group">
            <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
	<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>
    </div>

</div>

views/site/footer.php
<footer class="pg-footer pg-section">
	<div class="inner clearfix">
		<div class="pg-footer-left-30">
			<div class="logo-wrap logo-wrap-small">
				<a href="/" class="logo">Eventblaster</a>
				<p>Не тратьте время на поиск организатора, он сам Вас найдёт!</p>
				<center>
					<a href="/news" class="btn" style="font-size: 0.857em;">Следите за новостями</a>
					<!--<h1 style="margin:3% 0 0;font-size: 30px;">8 (800) 555-3535</h1>
					<h4 style="margin:0;">Нужна помощь? Мы поможем!</h4>-->
				</center>
			</div>
		</div>
		<div class="pg-footer-right-30">
			<nav class="footer-nav">
				<ul>
					<center><li><a href="/site/contact" class="btn">Ваши пожелания и отзывы</a></li>
					<li><a href="/support" class="btn">Служба поддержки</a></li>
					<li><a href="/contacts" class="btn">Контакты</a></li></center>
				</ul>
			</nav>
		</div>
		<div class="pg-footer-right-40">
			<h4>Мы в социальных сетях:</h4>
			<ul class="stat-list" style="margin-top:0">
				<li><a href="https://www.facebook.com/Eventblaster-%D0%92%D1%8B%D0%B1%D0%B5%D1%80%D0%B8-%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%B3%D0%BE-%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80%D0%B0-449921525205720/info/?tab=overview" target="_blanc"><img src="/img/facebook_icon_white.png" style="width:45px;"></a></li>
				<li><a href="https://www.instagram.com/eventblaster.ru/" target="_blanc"><img src="/img/insta_icon_white.png" style="width:45px;"></a></li>
				<li><a href="https://vk.com/blaster_event" target="_blanc"><img src="/img/vk_icon_white.png" style="width:45px;"></a></li>
				<li><a href="https://www.youtube.com/watch?v=O3Zddla2vT4" target="_blanc"><img src="/img/youtube_icon_white.png" style="width:45px;"></a></li>
			</ul>
			<p><small>© 2015-2016 Все права защищены.</small></p>
			<p><a href="/partner">Партнерская программа</a></p>
		</div>
	</div>
</footer>
<!— Yandex.Metrika counter —> 
<script type="text/javascript"> 
(function (d, w, c) { 
(w[c] = w[c] || []).push(function() { 
try { 
w.yaCounter34840430 = new Ya.Metrika({ 
id:34840430, 
clickmap:true, 
trackLinks:true, 
accurateTrackBounce:true, 
webvisor:true 
}); 
} catch(e) { } 
}); 

var n = d.getElementsByTagName("script")[0], 
s = d.createElement("script"), 
f = function () { n.parentNode.insertBefore(s, n); }; 
s.type = "text/javascript"; 
s.async = true; 
s.src = "https://mc.yandex.ru/metrika/watch.js"; 

if (w.opera == "[object Opera]") { 
d.addEventListener("DOMContentLoaded", f, false); 
} else { f(); } 
})(document, window, "yandex_metrika_callbacks"); 
</script> 
<noscript><div><img src="https://mc.yandex.ru/watch/34840430" style="position:absolute; left:-9999px;" alt="" /></div></noscript> 
<!— /Yandex.Metrika counter —>

views/site/greetings.php
<?
use app\models\User;
?>
<? if(User::isThisRole(User::TYPE_CLIENT)) { ?>
<? $messages = [
	'Организуйте мероприятие в один клик! Разместите заказ, и предложения сами будут приходить Вам по любым выбранным Вами средствам связи!',
	'Обращайте внимание на отзывы об организаторах мероприятий, а так же на рейтинг организаторов.',
	'Обязательно оставляйте отзывы организаторам мероприятий! Это поможет всем людям знать реальную правду!'
];

$message = $messages[rand(0, count($messages)-1)];

?>
<div class="rounded-greetings"><?=$message?> <div class="triangle"></div>
</div>
<img src="/img/p4.png" alt="">
<? } else { ?>
<? $messages = [
	'Заполните ваш профиль, что бы ваша страница получала наибольшее количество просмотров!',
	'Обязательно обращайте внимание на то, какие контакты заказчика доступны Вам для связи. Чем больше контактов доступно, тем больше заказчик предрасположен к предложениям!',
	'Обращайте внимание на детали заказа и дату проведения мероприятия!'
];
$message = $messages[rand(0, count($messages)-1)];

?>
<div class="rounded-greetings"><?=$message?> <div class="triangle"></div>
</div>
<img src="/img/p3.png" alt="">
<? } ?>

views/site/header.php
<?
namespace app\models;

use Yii;
use yii\widgets\Menu;
	
$user = Yii::$app->user->getIsGuest() ? false : User::findIdentity(Yii::$app->user->id);
$fio = ($user && $user->fio) ? '(' . $user->fio . ')' : '';
$usertype = $user ? $user->user_type_id . ')': false;
?>
<div class="reg-enter-wrap header">
	<div class="inner clearfix">
		<div class="logo-wrap logo-wrap-small"><a href="/" class="logo">Eventblaster</a><p>Не тратьте время на поиск организатора, он сам Вас найдёт!</p></div>
		<div class="reg-enter-list main-menu">
			<? echo Menu::widget([
			    'items' => [

			    		['label'=>'Главная', 'url'=>['site/index'], 'options'=>['class'=>'home'], 'visible'=>($user !== false) && ($usertype == User::TYPE_ADMIN)],
						// меню админа
			    		['label'=>'Пользователи', 'url'=>['userlist/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Отзывы', 'url'=>['reviews/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Заказы', 'url'=>['orders/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Типы услуг', 'url'=>['eventtype/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Теги', 'url'=>['tags/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Письма', 'url'=>['mailtemplates/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Города', 'url'=>['regions/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Страницы', 'url'=>['info/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Платежи', 'url'=>['payments/transactions'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Типы подписок', 'url'=>['payments/types'], 'visible'=>($usertype == User::TYPE_ADMIN)],
			    		['label'=>'Настройки', 'url'=>['settings/index'], 'visible'=>($usertype == User::TYPE_ADMIN)],

						// меню заказчика
			    		['label'=>'Мои заказы', 'url'=>['orders/index'], 'options'=>['class'=>'orders'], 'visible'=>($usertype == User::TYPE_CLIENT)],
			    		['label'=>'Предложения от организаторов', 'url'=>['message/deals'], 'options'=>['class'=>'filter'], 'visible'=>($usertype == User::TYPE_CLIENT)],
			    		['label'=>'Каталог организаторов', 'url'=>['userlist/index'], 'options'=>['class'=>'search'], 'visible'=>($usertype == User::TYPE_CLIENT)],
			    		['label'=>'Избранное', 'url'=>['userlist/favs'], 'options'=>['class'=>'favs'], 'visible'=>($usertype == User::TYPE_CLIENT)],

						// меню исполнителя
			    		['label'=>'Поиск заказов', 'url'=>['orders/index'], 'visible'=>($usertype == User::TYPE_SERVER)],
			    		['label'=>'Избранные заказы', 'url'=>['orders/favs'], 'options'=>['class'=>'favs'], 'visible'=>($usertype == User::TYPE_SERVER)],

						// общие пункты заказчика и исполнителя
			    		['label'=>'Мои сообщения', 'url'=>['message/index'], 'options'=>['class'=>'messages'], 'visible'=>($usertype == User::TYPE_CLIENT) ||($usertype == User::TYPE_SERVER)],
			    		['label'=>'Мой профиль', 'url'=>['user/view', 'id'=>$user ? $user->id : 0], 'visible'=>($usertype == User::TYPE_CLIENT) ||($usertype == User::TYPE_SERVER)],

						// общие пункты
			    		['label'=>'Каталог организаторов', 'url'=>['userlist/index'], 'options'=>[], 'visible'=>($user === false)],
			    		['label'=>'Список заказов', 'url'=>['orders/index'], 'options'=>[], 'visible'=>($user === false)],
			    		['label'=>'Регистрация', 'url'=>['user/register'], 'options'=>['class'=>'register'], 'visible'=>($user === false)],
			    		['label'=>'Вход', 'url'=>['user/login'], 'options'=>['class'=>'login'], 'visible'=>($user === false)],
			    		['label'=>'Выход '.$fio.'', 'url'=>['user/logout'], 'options'=>['class'=>'login'], 'visible'=>($user !== false)]
			    	]
		    	]
		    ); ?>
		    <div class="subscription pull-right">
				<? if($user && $user->_paid_now) { ?>
					Подписка оплачена до: <? echo date('d-m-Y H:i', $user->pay_until) ?>
				<? } ?>
    	
		    </div>
		</div>
	</div>
</div>
<? if(Yii::$app->session->hasFlash('header-messages')){ ?>
	<section class="help regform" id="help" style="color:black;text-align:left;box-shadow: 0 0 25px 5px; margin: 0 auto;">
		
		<? echo Yii::$app->session->getFlash('header-messages') ?>
		<p><a class="btn" onclick="jQuery('#help').slideUp(500)">Закрыть</a></p>
	</section>
<? } ?>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Eventblaster - организуйте мероприятие в один клик!';
?>
	<header class="home-header-wrap pg-section">
		<div class="inner">
			<div class="logo-wrap"><a href="/" class="logo">Eventblaster</a></div>
			<p>Не тратьте время на поиск организатора, он сам Вас найдёт!</p>
		</div>
	</header>
	<section class="intro-wrap pg-section">
		<div class="inner clearfix">
			<div class="intro-item intro-left clearfix">
				<div class="intro-img"><img src="/img/p3.png"></div>
				<div class="white-section">
					<div class="arrow-left"></div>
					<p>Мне нужно организовать<br>мероприятие!</p>
					<p><a onclick="showModal(1, &quot;#modal_form&quot;)" class="btn" style="cursor:pointer;">Заказать услуги</a></p>
				</div>
			</div>
			<div class="intro-item intro-right clearfix">
				<div class="intro-img"><img src="img/p4.png"></div>
				<div class="white-section">
					<div class="arrow-right"></div>
					<p>Я могу организовать<br>мероприятие!</p>
					<p><a onclick="showModal(2, &quot;#modal_form&quot;)" class="btn" style="cursor:pointer;">Предложить услуги</a></p>
				</div>
			</div>
		</div>
	</section>
	<section class="how-we-work pg-section">
		<div class="inner">
			<h2>Как работает сервис?</h2>
			<ul class="how-we-work-list">
				<li>
					<span>1</span>
					<div class="hww-img"><img src="/img/i3.png"></div>
					<p>Размещаете заказ<br>на мероприятие</p>
				</li>
				<li>
					<span>2</span>
					<div class="hww-img"><img src="/img/i2.png"></div>
					<p>Получаете предложения</p>
				</li>
				<li>
					<span>3</span>
					<div class="hww-img"><img src="/img/i1.png"></div>
					<p>Выбираете лучшее</p>
				</li>
			</ul>
			<footer>
				<h2>Как это выглядит?</h2>
				<iframe class="video-cl" src="https://www.youtube.com/embed/O3Zddla2vT4?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen=""></iframe>
			</footer>
		</div>
	</section>
	<section id="proj-count" class="intro-wrap pg-section">
		<h2>Немного о нас</h2>
		<div class="inner clearfix">
			<div class="intro-item intro-left clearfix">
				<div class="intro-img"><img src="/img/p3.png"></div>
				<div class="white-section">
					<div class="arrow-left"></div>
					<div class="home-count"><?=$orders+25 ?></div>
					<p class="mt-none">Размещенных заказов</p>
					<p><a onclick="showModal(1, &quot;#modal_form&quot;)" class="btn" style="cursor:pointer;">Хочу мероприятие!</a></p>
				</div>
			</div>
			<div class="intro-item intro-right clearfix">
				<div class="intro-img"><img src="/img/p4.png"></div>
				<div class="white-section">
					<div class="arrow-right"></div>
					<div class="home-count"><?=$servitors+36?></div>
					<p class="mt-none">Организаторов мероприятий</p>
					<p><a onclick="showModal(2, &quot;#modal_form&quot;)" class="btn" style="cursor:pointer;">Организую мероприятие!</a></p>
				</div>
			</div>
		</div>
	</section>
<? echo $this->renderFile('@app/views/site/modal_forms_index.php'); ?>

views/site/referal.php
<?
use yii\helpers\Url;
?>
<h3>Партнерская программа</h3>
<p>Ваша реферальная ссылка для партнерской программы: <?=Yii::$app->request->hostInfo . Url::toRoute(['site/ref', 'id'=>Yii::$app->user->id])?></p>
<p>Ваши начисления по партнерской программе:
	<a class="btn btn-default" href="<?=Yii::$app->request->hostInfo . Url::toRoute(['refs/view', 'id'=>Yii::$app->user->id])?>">Показать</a>
</p>