controllers/ReviewsController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\ImportedReviews;
use Yii;
use yii\helpers\Url;
use app\models\User;


class ReviewsController extends Controller {

    public function beforeAction($action){
		User::requireAdminAccess();	
		return parent::beforeAction($action);
    }

	public function actionIndex(){

		Yii::$app->user->setReturnUrl(Yii::$app->request->getUrl());

		$provider = new ActiveDataProvider([
		    'query' => ImportedReviews::find(),
			'sort'=> ['defaultOrder' => ['id'=>SORT_DESC]],
		    'pagination' => [
		        'pageSize' => 20,
		    ]
		]);
		return $this->render('index',
		[
			'dataProvider' => $provider,
		]);
	}

	public function actionRemove($id){
		$model = ImportedReviews::findByPk($id);
		$model->delete();
		return $this->goBack();
	}

	public function actionView($id, $parent = 0){
		
		if($id == 'new'){
			$model = new ImportedReviews();
		} else {
			$model = ImportedReviews::findByPk($id);
		}
    	if($model->load(Yii::$app->request->post())){
    		if(isset(Yii::$app->request->post()['save']))
	    		$model->save();
			$this->goBack();
    	}

		return $this->render('view', ['model'=>$model]);
	}

	
	
}
?>

views/reviews/index.php
<?
use yii\grid\GridView;
use app\models\User;
use yii\helpers\Url;

$this->title = 'Перенос отзывов с других сайтов';

?>
<div class="inner-section clearfix">
	<a href="<? echo Url::toRoute(['reviews/view', 'id'=>'new'])?>">Добавить</a>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        '_servitor.fio',
        'name',
        'text',
		'_created',
        [
        	'content' => function($model){
        		return ''.
        			'<a href="'.Url::toRoute(['reviews/view', 'id'=>$model->id]).'">Редактировать</a> '.
        			'<a href="'.Url::toRoute(['reviews/remove', 'id'=>$model->id]).'">Удалить</a>'.
        			'';
        	}
        ]
    ],
]) ?>
</div>

views/reviews/view.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\User;
use kartik\date\DatePicker;


$this->title = 'Редактирование отзыва - Перенос отзывов с других сайтов';

?>
<div class="inner-section clearfix">
<? $form = ActiveForm::Begin(); ?>
<? echo $form->field($model, 'servitor_id')->dropDownList(
	User::GetList()
); ?>
<? echo $form->field($model, 'name')->textInput(); ?>
<? echo $form->field($model, '_created')->widget(DatePicker::classname(), [
				'language' => 'ru',
				'removeButton' => false,
			    'pluginOptions' => [
			        'autoclose'=>true,
			        'format' => 'dd-mm-yyyy'
			    ]
		]); ?>
<? echo $form->field($model, 'text')->textArea(); ?>

<?= Html::submitButton('Сохранить', ['name'=>'save', 'class' => 'btn btn-primary']) ?>&nbsp;
<?= Html::submitButton('Назад', ['name'=>'back', 'class' => 'btn btn-primary']) ?>

<? ActiveForm::end(); ?>
</div>