models/Regions.php
<?php
namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\Url;
use app\models\User;

class Regions extends ActiveRecord {
    public static function tableName()
    {
        return 'regions';
    }
    
    public function rules(){
    	return [
    		[['title'], 'required']
    		];
    }
    
    public static function findByPk($id){
    	return self::findOne(['id'=>$id]);
    }

    public static function findByName($title){
    	return self::find()->where(['title'=>$title])->one();
    }

    public static function GetList($self_id = -1){
    	$retval = ($self_id != 0) ? ['0'=>'Верхний уровень'] : [];
    	foreach(self::find()->where(['moderated'=>1])->orderBy('title')->all() as $i){
    		if($i->id != $self_id)
	    		$retval[$i->id] = $i->title;
    	}
    	return $retval;
    }
    
    public static function AddNewVals($vals){
    	
		$retval = [];
    	if(is_array($vals))foreach($vals as $title){
    		$t = self::find()->where(['or', ['title'=>$title], ['id'=>$title]])->one();
    		if($t){
    			$retval[] = $t->id;
    			continue;
    		}
    		$t = new self();
    		$t->title = $title;
    		$t->insert();
    		$retval[] = $t->id;
    	}
    	
    	return $retval;

    }


}

controllers/RegionsController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Regions;
use Yii;
use yii\helpers\Url;
use app\models\User;


class RegionsController extends Controller {

    public function beforeAction($action){
		User::requireAdminAccess();	
		return parent::beforeAction($action);
    }

	public function actionIndex(){

		$provider = new ActiveDataProvider([
		    'query' => Regions::find()->orderBy('title'),
		    'pagination' => [
		        'pageSize' => 20,
		    ]
		]);
		
		Yii::$app->getUser()->setReturnUrl(Yii::$app->request->url);
		
		return $this->render('index',
		[
			'dataProvider' => $provider
		]);
	}

	public function actionModeration(){

		$provider = new ActiveDataProvider([
		    'query' => Regions::find()->where(['moderated'=>0])->orderBy('title'),
		    'pagination' => [
		        'pageSize' => 20,
		    ]
		]);
		
		Yii::$app->getUser()->setReturnUrl(Yii::$app->request->url);
		
		return $this->render('index',
		[
			'dataProvider' => $provider
		]);
	}

	public function actionApprove($id){
		$model = Regions::findByPk($id);
		if($model){
			$model->moderated = 1;
			$model->save();
		}
		$this->goBack();
	}

	public function actionRemove($id){
		$model = Regions::findByPk($id);
		if($model){
			$model->delete();
		}
		$this->goBack();
	}


	public function actionView($id){
		
		if($id == 'new'){
			$model = new Regions();
		} else {
			$model = Regions::findByPk($id);
		}
    	if($model->load(Yii::$app->request->post())){
    		$model->save();
    		if(isset(Yii::$app->request->post()['save']))
    			$this->goBack();
    	}

		return $this->render('view', ['model'=>$model]);
	}

	
	
}
?>

views/regions/index.php
<?
use yii\grid\GridView;
use yii\helpers\Url;

?>
<div class="inner-section clearfix">
	<a href="<? echo Url::toRoute(['regions/view', 'id'=>'new'])?>">Добавить</a>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'title',
        [
        	'content' => function($model){
        		$actions = '<a href="'.Url::toRoute(['regions/view', 'id'=>$model->id]).'">Редактировать</a> ';
        		$actions .= '<a href="'.Url::toRoute(['regions/remove', 'id'=>$model->id]).'">Удалить</a> ';
        		if(!$model->moderated)
	        		$actions .= '<a href="'.Url::toRoute(['regions/approve', 'id'=>$model->id]).'">Утвердить</a> ';
	        		
        		return $actions;
        		
        	}
    	]
    ],
]) ?>
</div>

views/regions/view.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\UserTypes;
use dosamigos\ckeditor\CKEditor;


?>
<div class="inner-section clearfix">
<? $form = ActiveForm::Begin(); ?>
<? echo $form->field($model, 'title')->textInput(); ?>
<?= Html::submitButton('Сохранить', ['name'=>'save', 'class' => 'btn btn-primary']) ?>

<? ActiveForm::end(); ?>
</div>